server:
  port: 7100
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/stockmanagement
    username: root
    password:
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        format_sql: true
    show-sql: true

flickr:
  apiKeys: cedc9549140db37eb59b27d51e2782d4
  apiSecret: 18fde413460fb56f


